### ISSUE TITLE
CAN data does not show values

### ISSUE THREAD

**Issue by j-antunes** [PlotJuggler/plotjuggler-CAN-dbs#10]
Hello!

I have a can data file and a corresponding dbc file.
I saved this file by doing `candump -L can0 > myfile.log`
I then load the file and the dbc file into the UI, but it shows that there are no values. When I try to plot one of the CAN field it only plots one value. 

I noticed that on the TimeSeriesList tree view, on the right side where it should display "values" it shows a "-". See image.
![image](https://user-images.githubusercontent.com/64033582/167163916-96a158fc-378d-4543-9127-9b8169d6521a.png)

I verified and the CAN file has values and I can plot them using matplotlib.

Please let me know if you have any suggestion.

My machine is running Ubuntu 20.04, and I built plotjuggler and plotjuggler-can-dbs

Note: I tested with the provided files: https://github.com/PlotJuggler/plotjuggler-CAN-dbs/tree/development/datasamples and it's working for these ones.

**Comment by ozzdemir** [comment]
Hi, I have a possible culprit in mind for the problem you described. But It would be really good if you were to share an example CAN log for verification and testing.

**Comment by j-antunes** [comment]
Thank you for the prompt reply! I think the issue could be with my dbc file? I'll try to see if I can figure it out. If not I'll see if I can share a "stripped down" version of my dbc file that still reproduces the error.

**Comment by j-antunes** [comment]
What is a good email that I could send you an example?

**Comment by ozzdemir** [comment]
You can send it to oguz.ozdemir@ieee.metu.edu.tr

**Comment by ozzdemir** [comment]
I hope that you also received the comment via e-mail :)

**Comment by ozzdemir** [comment]
Hi @j-antunes , its been a while after our conversation. This issue might be resolved with #13 , can you check if it works for your case (i.e. J1939) ? I might work to finalize #13 and it would be nice to have someone test also for the J1939 (I mainly developed it to support NMEA2000, but it should work for J1939 with little to no modification.).

**Comment by j-antunes** [comment]
Hi @ozzdemir - Thanks for working on it. Unfortunantely, I'm not working on that project anymore and don't have the data in question. The sample that I sent you over email should work if you still have it.

**Comment by ozzdemir** [comment]
I tested with them after your reminder and it worked with only modifying source address in the dbc. Actually, I had some [questions](https://github.com/PlotJuggler/plotjuggler-CAN-dbs/blob/13-refactoring-and-partial-nmea2k-j1939-support/PluginsCommonCAN/CanFrameProcessor.cpp#L141) about null address (0xFE ) assumption, and seems it can be broken in the dbc. 

To me, using source address as NULL(0xFE) in a dbc still seems a legit convention, but I will check if it can be resolved anyway.

Thanks for your contribution :)

**Comment by ozzdemir** [comment]
Resolved this issue and the minor one that I mentioned about the source addresses etc. by using PGNs as the key for the messages for the J1939 and NMEA2K case in the  [5082004](https://github.com/PlotJuggler/plotjuggler-CAN-dbs/commit/5082004bd943fab1e9e73f7f9446ad6ab91ea2bb). So, closing.
