### ISSUE TITLE
Cannot open the log file

### ISSUE THREAD

**Issue by sabdulqadir** [PlotJuggler/plotjuggler-CAN-dbs#11]
Hi,
I am trying to use this plugin but could not make use of the existing steps in README.md. I could build both projects. Then I copied the "build" directory from ".../plotjuggler-CAN-dbs/build/" into ".../PlotJuggler/build/plotjuggler_plugins/" and renamed it "DataLoadCAN". Then I ran plotjuggler but could not import the sample log file from "/plotjuggler-CAN-dbs/datasamples/"
How exactly should that be done?

**Comment by sabdulqadir** [comment]
![plotJugglerNotWorking](https://user-images.githubusercontent.com/13925237/169622097-34279dab-1938-4448-8f9d-5de3424a9a64.jpg)

**Comment by sabdulqadir** [comment]
Am i even doing the right thing here?

**Comment by ozzdemir** [comment]
By the following, I did not mean moving build folder around, but did mean https://github.com/facontidavide/PlotJuggler/issues/364#issuecomment-754590442

> After building the plugins, one needs to include build directory to the plugins directory of the PlotJuggler.

**Comment by sabdulqadir** [comment]
Thanks for the reply ozzdemir. That made sense. So i included the build directory and now when I try to load an example log data file, it does subsequently ask for a dbc file. Once provided, I can plot the static data.
Coming to the second concern then. How do I stream CAN data to PJ? My candump is working. But I do not see any option to stream CAN data into PJ. 
The streaming tab only has three options. 
1. MQTT
2. UDP
3. WebSocket
Thanks,
AQ

**Comment by ozzdemir** [comment]
For DataStreamCAN, please check https://github.com/PlotJuggler/plotjuggler-CAN-dbs#datastreamcan
DataStreamCAN plugin is only built if your Qt5 Installation has SerialBus plugin. Since your issue is resolved (the other one will also be resolved if you install SerialBus via mentioned gist), will close the issue.
